# Generated by Django 4.2.6 on 2025-11-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="matches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="won",
            field=models.BooleanField(default=False),
        ),
    ]
