# Generated by Django 4.2.6 on 2025-11-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_team_lost_team_matches_team_won"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammatch",
            name="lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teammatch",
            name="matches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teammatch",
            name="won",
            field=models.BooleanField(default=False),
        ),
    ]
