# Generated by Django 4.2.6 on 2025-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0003_teammatch_lost_teammatch_matches_teammatch_won"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="lost",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="team",
            name="won",
            field=models.IntegerField(),
        ),
    ]
