# Generated by Django 4.2.6 on 2025-11-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0004_alter_team_lost_alter_team_won"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammatch",
            name="matches",
        ),
        migrations.AlterField(
            model_name="team",
            name="lost",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="won",
            field=models.IntegerField(default=0),
        ),
    ]
