# Generated by Django 4.2.6 on 2025-11-05 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0005_remove_teammatch_matches_alter_team_lost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="lost",
        ),
        migrations.RemoveField(
            model_name="team",
            name="matches",
        ),
        migrations.RemoveField(
            model_name="team",
            name="won",
        ),
    ]
