# Generated by Django 4.2.6 on 2025-11-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0006_remove_team_lost_remove_team_matches_remove_team_won"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="lost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="matches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="won",
            field=models.IntegerField(default=0),
        ),
    ]
