# Generated by Django 4.2.6 on 2025-11-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0007_team_lost_team_matches_team_won"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammatch",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
