# Generated by Django 4.2.6 on 2025-11-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0008_teammatch_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammatch",
            name="points",
        ),
        migrations.AddField(
            model_name="team",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
