# Generated by Django 4.2.6 on 2025-11-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0010_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="country",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
